#!/usr/bin/env sh

# Creates a worktree in .worktrees/<name>, ready to work in.
#
# Usage:
#   scripts/new-worktree.sh <branch> [--name <name>] [--base <ref>] [--no-install]
#
# Example:
#   scripts/new-worktree.sh feat/units-cnes
#
# The worktree is named after the branch without its prefix (feat/units-cnes
# becomes .worktrees/units-cnes) and starts from origin/main unless --base says
# otherwise. Besides `git worktree add`, it:
#   - installs the dependencies, because the Git hooks are generated by the
#     install (husky) and the tests need node_modules;
#   - recreates the .claude/skills links, which Git ignores;
#   - copies the root .env from the main checkout, when there is one (Git
#     ignores it too). deploy/.env is never copied: it can hold production
#     credentials, and worktrees are often handed to agents.
#
# It never runs git add, git commit or git push. Local changes of the checkout
# it is run from do not move to the new worktree. What goes into a commit and
# into a push is decided by whoever works there, and anything outside the scope
# of the task is committed and pushed only when that is asked for explicitly.

set -eu

usage() {
  cat <<'EOF'
Uso: scripts/new-worktree.sh <branch> [--name <nome>] [--base <ref>] [--no-install]

Cria .worktrees/<nome> com uma branch nova, a partir de origin/main (ou de
--base), instala as dependências, recria os links de .claude/skills e copia o
.env da raiz, se existir (o deploy/.env não é copiado: pode ter credenciais de
produção). O nome é a branch sem o prefixo: feat/units-cnes vira
.worktrees/units-cnes.

  --name <nome>   nome da pasta, quando o derivado da branch colide com outro
  --base <ref>    ponto de partida da branch (padrão: origin/main)
  --no-install    não roda pnpm install --frozen-lockfile; os hooks do Git só
                  passam a existir depois do install
  -h, --help      mostra esta ajuda

O script não faz git add, commit nem push.
EOF
}

die() {
  echo "Erro: $1" >&2
  exit 1
}

# An option value must be present and must not look like another option.
need_value() {
  [ $# -ge 2 ] && [ -n "$2" ] && [ "${2#-}" = "$2" ] \
    || die "$1 precisa de um valor."
}

branch=""
name=""
base="origin/main"
install=1
base_stale=0

while [ $# -gt 0 ]; do
  case "$1" in
    -h | --help)
      usage
      exit 0
      ;;
    --no-install)
      install=0
      ;;
    --name)
      need_value "$@"
      name=$2
      shift
      ;;
    --base)
      need_value "$@"
      base=$2
      shift
      ;;
    -*)
      die "opção desconhecida: $1"
      ;;
    *)
      [ -z "$branch" ] || die "informe uma única branch."
      branch=$1
      ;;
  esac
  shift
done

if [ -z "$branch" ]; then
  usage >&2
  exit 1
fi

git rev-parse --git-dir >/dev/null 2>&1 || die "execute dentro do repositório."
git check-ref-format --branch "$branch" >/dev/null 2>&1 \
  || die "nome de branch inválido: $branch"

# The first entry of the list is always the main checkout, wherever this runs.
main_root=$(git worktree list --porcelain | sed -n 's/^worktree //p' | head -n 1)

if [ -z "$name" ]; then
  name=${branch#*/}
  name=$(printf '%s' "$name" | tr '/' '-')
fi
printf '%s' "$name" | grep -Eq '^[A-Za-z0-9][A-Za-z0-9._-]*$' \
  || die "não consegui derivar um nome de pasta válido. Use --name."

target="$main_root/.worktrees/$name"
[ ! -e "$target" ] \
  || die ".worktrees/$name já existe. Se ela ficou sem dependências, entre nela e rode pnpm install --frozen-lockfile. Para outra tarefa com nome parecido, escolha outro com --name."
if git show-ref --verify --quiet "refs/heads/$branch"; then
  die "a branch $branch já existe. Para usá-la: git worktree add .worktrees/$name $branch"
fi
# Ask the remote itself, not the local remote-tracking ref (which outlives a
# deleted branch). Exit status 2 means "not there"; anything else means origin
# could not be reached, and then the check is skipped, loudly.
remote_unchecked=0
if git ls-remote --exit-code --heads origin "$branch" >/dev/null 2>&1; then
  [ "$base" = "origin/$branch" ] \
    || die "a branch $branch já existe em origin. Para continuar o trabalho dela: scripts/new-worktree.sh $branch --base origin/$branch"
else
  if [ $? -ne 2 ]; then
    remote_unchecked=1
    echo "Aviso: não consegui consultar origin; não sei se $branch já existe lá." >&2
  fi
fi

# Offline, or with another remote name, the local ref is still usable.
case "$base" in
  origin/*)
    echo "Atualizando $base..."
    git fetch --quiet origin "${base#origin/}" || {
      base_stale=1
      echo "Aviso: não consegui atualizar $base; usando a referência local." >&2
    }
    ;;
esac
git rev-parse --verify --quiet "$base^{commit}" >/dev/null \
  || die "referência inexistente: $base"
base_commit=$(git rev-parse --short "$base^{commit}")

# Counted before the worktree exists, to say what stays behind.
local_changes=$(git status --porcelain | wc -l | tr -d ' ')
current_root=$(git rev-parse --show-toplevel)

# --no-track: a plain `git push` must not aim at the base. The first push is
# explicit: git push -u origin HEAD.
git worktree add --quiet --no-track -b "$branch" "$target" "$base"

if [ -d "$target/.agents/skills" ]; then
  mkdir -p "$target/.claude/skills"
  for dir in "$target"/.agents/skills/*/; do
    [ -d "$dir" ] || continue
    skill=$(basename "$dir")
    if [ ! -e "$target/.claude/skills/$skill" ]; then
      ln -s "../../.agents/skills/$skill" "$target/.claude/skills/$skill"
    fi
  done
fi

# Only the root .env, which holds local development defaults. Never deploy/.env.
env_copied=0
if [ -f "$main_root/.env" ] && [ ! -e "$target/.env" ]; then
  cp -p "$main_root/.env" "$target/.env"
  env_copied=1
fi
# Other ignored .env files stay behind on purpose; say which, so it is not silent.
env_skipped=$(
  find "$main_root" -maxdepth 4 -name .env -type f \
    -not -path '*/node_modules/*' -not -path '*/.worktrees/*' 2>/dev/null \
    | while IFS= read -r file; do
      relative=${file#"$main_root"/}
      [ "$relative" = ".env" ] || echo "$relative"
    done
)

hooks_ready=1
install_failed=0
if [ "$install" -eq 1 ]; then
  if command -v pnpm >/dev/null 2>&1; then
    echo "Instalando dependências..."
    if ! (cd "$target" && pnpm install --frozen-lockfile); then
      hooks_ready=0
      install_failed=1
    fi
  else
    echo "pnpm não encontrado." >&2
    hooks_ready=0
    install_failed=1
  fi
else
  hooks_ready=0
fi

echo
if [ "$install_failed" -eq 1 ]; then
  echo "Worktree criada, mas SEM as dependências instaladas: .worktrees/$name"
else
  echo "Worktree criada: .worktrees/$name"
fi
echo "  branch: $branch (a partir de $base, $base_commit)"
echo "  entrar: cd $target"
[ "$env_copied" -eq 0 ] || echo "  .env copiado da checkout principal (ignorado pelo Git)."
if [ -n "$env_skipped" ]; then
  echo "  não copiado de propósito (copie à mão se a tarefa precisar): $(echo "$env_skipped" | tr '\n' ' ')"
fi
echo
echo "Lembretes:"
if [ "$base_stale" -eq 1 ]; then
  echo "  - ATENÇÃO: não consegui atualizar $base; a worktree parte da referência local"
  echo "    ($base_commit) e pode estar atrasada. Confira com git fetch antes de abrir a PR."
fi
if [ "$install" -eq 0 ]; then
  echo "  - ATENÇÃO: a instalação foi pulada, então os hooks do Git (lint no commit,"
  echo "    verificação completa no push) NÃO existem nesta worktree."
  echo "    Rode, antes de commitar: cd .worktrees/$name && pnpm install --frozen-lockfile"
fi
if [ "$remote_unchecked" -eq 1 ]; then
  echo "  - ATENÇÃO: não consegui consultar origin. Se $branch já existir lá, o primeiro"
  echo "    push será rejeitado; confira com git ls-remote --heads origin $branch."
fi
echo "  - A worktree parte de $base ($base_commit), não do HEAD de $current_root:"
echo "    commits e alterações que só existem lá não vêm junto."
if [ "$local_changes" -gt 0 ]; then
  echo "  - $current_root tem $local_changes alteração(ões) local(is) não commitada(s), incluindo arquivos novos."
fi
echo "  - Nada foi adicionado, commitado nem enviado. Arquivos fora do escopo da tarefa"
echo "    só entram em commit e push quando isso for pedido de forma explícita."
echo "    Adicione por caminho (git add <arquivo>); evite git add -A, git add . e git commit -a."
echo "  - Primeiro envio: git push -u origin HEAD"
echo "  - Ao terminar: git worktree remove .worktrees/$name && git worktree prune"

# The worktree exists, but a caller (or an agent) must be able to tell it is
# not ready.
if [ "$install_failed" -eq 1 ]; then
  echo "Erro: a instalação das dependências falhou; a worktree existe, mas não está pronta." >&2
  echo "Não rode o script de novo: entre em .worktrees/$name e rode pnpm install --frozen-lockfile." >&2
  exit 1
fi
